export enum helper {
  FULL_NAME = 'Farhan Fazli',
  CURRENT_TITLE = 'Senior Software Engineer',
  MOBILE_NO = '+60124940907',
  WEBSITE = 'https://paanjoe.com',
  EMAIL = 'farhan.gunz@gmail.com',
  LOCATION = 'Kuala Lumpur, Malaysia',
  PROFILEPIC_URL = 'https://scontent.fkul8-1.fna.fbcdn.net/v/t39.30808-6/277305549_7892412894117547_3394979653194414044_n.jpg?_nc_cat=104&ccb=1-5&_nc_sid=09cbfe&_nc_ohc=VEosBkCsL_cAX9Njkst&_nc_ht=scontent.fkul8-1.fna&oh=00_AT-DDyWX8IYMuHT4Nu2azZbIpTekAOsJnwIKk92kblKWhg&oe=624AFD91',
  PROFILE_SUMMARY = 'An aspiring and enthusiastic "tech ninja". Able to contribute diverse ideas onto the table, having participated actively in a number of skill-demanding projects and obtained technical and managerial skills from fast-paced jobs/tasks, all while being a great father/husband at the same time. Dipped my toes in the modern IT technologies to understand and contribute to the fourth industrial revolution globally.',
  WORK_TITLE = 'PROFESSIONAL EXPERIENCES',
  SKILLS_TITLE = 'SKILLS',
  EDUCATION_TITLE = 'EDUCATION',
  ACHIEVEMENTS_TITLE = 'ACHIEVEMENTS/HOBBY PROJECTS',
  LANGUAGE_TITLE = 'LANGUAGES',
  INTEREST_TITLE = 'INTERESTS',
  PROJECTS_TITLE = 'PROJECTS',
  REFERREE_TITLE = 'REFERREE',
  GITHUB_URL = 'https://github.com/paanjoe',
  LINKEDIN_URL = 'https://www.linkedin.com/in/mohd-farhan-muhamad-fazli-693b7912b/',
}
